# Package Magager
[[plugins]]
repo = 'Shougo/dein.vim'


# UI, search
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins_dein/denite.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
#build_on = '''
#./install -all
#'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'mileszs/ack.vim'
## Themes, StatusLine

# statusline plugin
#[[plugins]]
#repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
source ~/.config/nvim/plugins_dein/vim-airline.vim
"let g:airline_theme = 'molokai'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

## colorscheme
#[[plugins]]
#repo = 'joshdick/onedark.vim'
#hook_add = '''
#colorscheme onedark
#'''


# File Tree

## Defx
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins_dein/defx.vim
nnoremap <silent> <Leader>f :<C-u> Defx <CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

## NERDTree
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# launch
[[plugins]]
repo = 'thinca/vim-quickrun'

# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

# editor utils

## block
[[plugins]]
repo = 'tpope/vim-endwise'

## Search
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugins_dein/anzu.vim
'''

## visual expand
[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

## tab
#[[plugins]]
#repo = 'ervandew/supertab'

## commentry
[[plugins]]
repo = 'tpope/vim-commentary'

## repeat
[[plugins]]
repo = 'tpope/vim-repeat'

## surround
[[plugins]]
repo = 'tpope/vim-surround'

## bracket
[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

## HTML, XML, ...
[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'mattn/emmet-vim'

## trailing-whitespace
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

## syntax
[[plugins]]
repo = 'sheerun/vim-polyglot'

## Syntax checker
[[plugins]]
repo = 'w0rp/ale'

## mark, tag
[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'jacquesbh/vim-showmarks'

### https://qiita.com/lighttiger2505/items/6b1cd3bc79cb9806a743
[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    " Options
    let g:Gtags_Auto_Map = 0
    let g:Gtags_OpenQuickfixWindow = 1
    " Keymap
    " Show definetion of function cousor word on quickfix
    nmap <silent> K :<C-u>exe("Gtags ".expand('<cword>'))<CR>
    " Show reference of cousor word on quickfix
    nmap <silent> R :<C-u>exe("Gtags -r ".expand('<cword>'))<CR>
'''
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
    let g:gen_tags#gtags_auto_gen = 1
'''

[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = '''
    " Prefix key
    nmap [denite] <Nop>
    map <C-j> [denite]
    " Keymap
    nmap <silent> [denite]<C-D> :Denite -buffer-name=gtags_completion gtags_completion<cr>
'''

