[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins_dein/denite.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
#build_on = '''
#./install -all
#'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins_dein/defx.vim
nnoremap <silent> <Leader>f :<C-u> Defx <CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugins_dein/anzu.vim
'''

# Syntax checker
[[plugins]]
repo = 'w0rp/ale'

# statusline plugin
#[[plugins]]
#repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
source ~/.config/nvim/plugins_dein/vim-airline.vim
"let g:airline_theme = 'molokai'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

## colorscheme
#[[plugins]]
#repo = 'joshdick/onedark.vim'
#hook_add = '''
#colorscheme onedark
#'''

[[plugins]]
repo = 'alvan/vim-closetag'

[[plugins]]
repo = 'sheerun/vim-polyglot'

