
# Defx

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/defx.nvim'
if = "has('nvim')"
build = ':UpdateRemotePlugins'
depends = ['defx-git', 'defx-icons']
on_cmd = 'Defx'
hook_add = '''
source ~/.config/nvim/plugins_dein/defx.vim
nnoremap <silent> <Leader>f :<C-u> Defx <CR>
'''

# Deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"
build = ':UpdateRemotePlugins'
# on_event = 'InsertEnter'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
hook_source = '''
source ~/.config/nvim/plugins_dein/deoplete.vim
'''
# hook_add = '''

# " 汚いが、OS毎の分岐を作るのは面倒そうなのでここでdeoplete-tabnineも入れてしまう
# " deoplete-tabnine
# if has('win32') || has('win64')
#   call dein#add('tbodt/deoplete-tabnine', { 'build': 'powershell.exe .\install.ps1' })
# else
#   call dein#add('tbodt/deoplete-tabnine', { 'build': './install.sh' })
# endif
# '''
# hook_post_source = '''
# " ToDo
# call deoplete#custom#source('TN', 'rank', 120)
# '''
# TNではdeopleteのrankを変えられていないかもしれない

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
on_event = 'InsertEnter'
hook_post_update = '''
if has('win32') || has('win64')
  let cmd = 'powershell.exe ./install.ps1'
else
  let cmd = './install.sh'
let g:dein#plugin.build = cmd
'''
hook_post_source = '''
" ToDo
call deoplete#custom#source('TN', 'rank', 120)
'''

# deoplete-vim-lspがあるが、普通にjediを使う方が現在は安定しそう
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_source = '''
let s:python3_project  = getenv("PYTHON3_PROJECT")
if s:python3_project != v:null
    let g:deoplete#sources#jedi#python_path = s:python3_project
endif
unlet s:python3_project
'''
hook_post_source = '''
" ToDo
call deoplete#custom#source('jedi', 'rank', 5000)
'''
# hook_postでもうまく働いていない? vim起動時に直接実行するとうまく働く様子

# pep8 indent
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

# python virtualenv
[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# on_ft = ['python']


# zsh
[[plugins]]
repo = 'deoplete-plugins/deoplete-zsh'
on_ft = 'zsh'


# Docker
# [[plugins]]
# repo = 'deoplete-plugins/deoplete-docker'
# on_ft = 'Docker'

# javascript
# deoplete-vim-lspがあるが、ternjsの方が有効なこともまだ多そうな感じ
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
build = 'npm install -g tern'
hook_post_source = '''
" ToDO
call deoplete#custom#source('TernJS', 'rank', 5000)
'''
# linuxのシステムのnpmだとsudoが必要になるので予め入れておく?

[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'ryanolsonx/vim-lsp-javascript'
on_ft = ['javascript']


# vim-lsp
[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_event = 'InsertEnter'
hook_source = '''
source ~/.config/nvim/plugins_dein/deoplete-vim-lsp.vim
'''
hook_post_source = '''
" ToDo
call deoplete#custom#source('lsp', 'rank', 6000)
'''


# tabnine (AI)
# [[plugins]]
# repo = 'tbodt/deoplete-tabnine'
# on_event = 'InsertEnter'
# build = '''
# ./install.sh
# '''

# DEBUG
# うまく読み込まれていない様子
# [[plugins]]
# repo = 'puremourning/vimspector'
# on_ft = ["python", "javascript", "sh", "bash"]
# build = "./install_gadget.py --enable-python --enable-bash --force-enable-chrome"
# hook_add = '''
# source ~/.config/nvim/plugins_dein/vimspector.vim
# '''

# snippets
repo = 'Shougo/neosnippet.vim'
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_post_source = '''
source ~/.config/nvim/plugins_dein/neosnippet.vim
'''


# LSP
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = [
    'python',
    'go',
    'typescript',
    'javascript',
    'c',
    'cpp',
    'sql',
    'vue',
    'sql',
]
depends = [
    'deoplete-vim-lsp',
    'vista.vim',
    'vim-lsp-typescript',
    'vim-lsp-javascript',
    'vim-lsp-settings',
    'vim-lsp-icons',
]
hook_source = '''
source ~/.config/nvim/plugins_dein/vim-lsp.vim
'''

[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'ryanolsonx/vim-lsp-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'mattn/vim-lsp-settings'
on_ft = [
    'python',
    'go',
    'typescript',
    'javascript',
    'c',
    'cpp',
    'sql',
    'vue',
    'sql',
]
hook_source = '''
source ~/.config/nvim/plugins_dein/vim-lsp-setting.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'
on_ft = [
    'python',
    'go',
    'typescript',
    'javascript',
    'c',
    'cpp',
    'sql',
    'vue',
    'sql',
]

# vista
repo = 'liuchengxu/vista.vim'
on_cmd = ['Vista']
hook_add = '''
source ~/.config/nvim/plugins_dein/vista.vim
'''
