[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
source ~/.config/nvim/plugins_dein/deoplete.vim
'''

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
#hook_add = '''
#    let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python3.6'
#'''


