[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
source ~/.config/nvim/plugins_dein/deoplete.vim
'''

# [[plugins]]
# repo = "davidhalter/jedi-vim"
# on_ft = ['python']


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = '''
let s:python3_project  = getenv("PYTHON3_PROJECT")
if s:python3_project != v:null
    let g:deoplete#sources#jedi#python_path = s:python3_project
endif
unlet s:python3_project
'''

# pep8 indent
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'


[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
build = 'npm install -g tern'
# linuxのシステムのnpmだとsudoが必要になるので予め入れておく?


