[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins_dein/denite.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
#build_on = '''
#./install -all
#'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.config/nvim/plugins_dein/defx.vim
'''

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugins_dein/anzu.vim
'''

# Syntax checker
[[plugins]]
repo = 'w0rp/ale'

# statusline plugin
[[plugins]]
repo = 'itchyny/lightline.vim'

## colorscheme
#[[plugins]]
#repo = 'joshdick/onedark.vim'
#hook_add = '''
#colorscheme onedark
#'''

[[plugins]]
repo = 'alvan/vim-closetag'

